package tommy.naivedialog;

/**
 * @author : Tommy
 */
public enum Type {
    POPUP, DIALOG_FRAGMENT_1, DIALOG_FRAGMENT_2, DIALOG_FRAGMENT_3,
    DIALOG_FRAGMENT_4, DIALOG_FRAGMENT_5, DIALOG_FRAGMENT_6, DIALOG_FRAGMENT_7,
    DIALOG_FRAGMENT_8, DIALOG_FRAGMENT_9, DIALOG_FRAGMENT_10, DIALOG_FRAGMENT_11
}
